import React, { useState } from 'react';

function Skills(props) {
    const [isShown, setIsShown] = useState(false);
  
    return (
      <div className="component-skills">
        <div 
          onMouseEnter={() => setIsShown(true)}
          onMouseLeave={() => setIsShown(false)}>
          
        {isShown && (
          <div >
              <h3>{props.nom}</h3>
              <div className="skills-progress">
<label>{props.label1}</label>
<progress max="100" value={props.value1}>{props.progress1}</progress>
<br/>
<label>{props.label2}</label>
<progress max="100" value={props.value2}>{props.progress2}</progress>
<br/>
<label>{props.label3}</label>
<progress max="100" value={props.value3}>{props.progress3}</progress>
<br/></div>
          </div>
         
        )}
         {!isShown && (
          <div className="yoy">
<h3>{props.nom}</h3>
<button className="btn-hover">Hover me!</button>
         </div>
        )}
        
        
        </div> 
      </div>
    );
  }

export default Skills


// CSS File 

/* SKILLS JS Version #1 */
/* 

.box-skills{
  flex-direction: row;
  display: flex;
  justify-content: space-around;
  padding: 4%;
}

.component-skills{
  padding: 1%;
  width: 33.3%;
  height: 100px;
}

.skills-progress{
  text-align: right;
  margin-right: 15%;
}

.skills-progress label {
  width: 150px;
  margin-right: 5%;
}

.skills-progress progress {
  width: 40%;
}

.btn-hover{
  width: 20%;
  color: black;
  padding: 3% 5%;
  margin-top: 2%;
  border: solid black 1px;
} */


/* .flip-horizontal-bottom {
	-webkit-animation: flip-horizontal-bottom 0.4s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
	        animation: flip-horizontal-bottom 0.4s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
} */

/* ----------------------------------------------
 * Generated by Animista on 2021-7-13 15:53:48
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/* 
/**
 * ----------------------------------------
 * animation flip-horizontal-bottom
 * ----------------------------------------
 */
 /* @-webkit-keyframes flip-horizontal-bottom {
  0% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
  }
  100% {
    -webkit-transform: rotateX(-180deg);
            transform: rotateX(-180deg);
  }
}
@keyframes flip-horizontal-bottom {
  0% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
  }
  100% {
    -webkit-transform: rotateX(-180deg);
            transform: rotateX(-180deg);
  }
} */ 
